version: 0.2

phases:
  build:
    commands:
      - cd go-example-logs-api-extension
      - GOOS=linux GOARCH=amd64 go build -o bin/extensions/go-example-logs-api-extension main.go
      - chmod +x bin/extensions/go-example-logs-api-extension
      - cd bin
      - zip -r extension.zip extensions/
artifacts:
  files:
    - update-last-acted-graal.cf.yml