AWSTemplateFormatVersion: 2010-09-09
Description: The top level service pipeline to create the management deployment pipelines for dev
Parameters:
  GitBranch:
    Type: String
    Default: main
  AutoSource:
    Description: Do you want to create a web-hook to automatically look for changes to this repo
    Type: String
    AllowedValues:
      - True
      - False
    Default: True
  DeployAccount:
    Description: AWS account number to deploy infrastructure to
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/account/dev"
  ServiceOwner:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/service/owner"
  ServiceCode:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/service/code"
  ServiceName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/service/name"
  ArtifactBucket:
    Description: The artifact bucket ssm
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/artifact/bucket"
  KmsKey:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "/nswws-meteo/kms/arn"
  # ------------------------
Resources:
  DeployGolangExtensionPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: deploy-golang-extension-pipeline
      RestartExecutionOnUpdate: true
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/PipelineAutomationRole
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
        EncryptionKey:
          Id: !Ref KmsKey
          Type: KMS
      Stages:
        - Name: Source
          Actions:
            - ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Owner: mo-rjr
                Repo: aws-lambda-extensions
                PollForSourceChanges: false
                Branch: master
                OAuthToken: '{{resolve:secretsmanager:/github/token:SecretString:mo-rjr}}'
              Name: extensions_src
              OutputArtifacts:
                - Name: extensions_src
        # ----------------------------------------------------------------------------------------------------------------------------
        - Name: Build
          Actions:
            - Name: CreateCodeBuildProject
              RunOrder: 1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              InputArtifacts:
                - Name: extensions_src
              Configuration:
                ActionMode: REPLACE_ON_FAILURE
                Capabilities: CAPABILITY_NAMED_IAM
                RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/PipelineAutomationRole
                StackName: "extension-build-project"
                TemplatePath: extensions_src::go-example-logs-api-extension/build-project.yml
                ParameterOverrides: !Sub |
                  {
                    "DeployAccount": "${DeployAccount}",
                    "ServiceOwner": "${ServiceOwner}",
                    "ServiceCode": "${ServiceCode}",
                    "ServiceName": "${ServiceName}",
                    "ArtifactBucket": "${ArtifactBucket}"
                  }
            - Name: BuildProject
              RunOrder: 5
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: "1"
                Provider: CodeBuild
              InputArtifacts:
                - Name: extensions_src
              OutputArtifacts:
                - Name: source_built
              Configuration:
                ProjectName: "extension-build-project"

        # ----------------------------------------------------------------------------------------------------------------------------
        - Name: Deploy
          Actions:
            - Name: ExtensionLayerChangeSet
              RunOrder: 10
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              InputArtifacts:
                - Name: source_built
              RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
              Configuration:
                ChangeSetName: "extension-layer-change-set"
                StackName: "extension-layer"
                ActionMode: CHANGE_SET_REPLACE
                RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: source_built::go-example-logs-api-extension/built-extension.yml
                ParameterOverrides: !Sub |
                  {
                    "ServiceOwner": "${ServiceOwner}",
                    "ServiceCode": "${ServiceCode}",
                    "ServiceName": "${ServiceName}"
                  }
            - Name: DeployAtomWatcherChangeSet
              RunOrder: 20
              RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: "1"
                Provider: CloudFormation
              Configuration:
                ChangeSetName: "extension-layer-change-set"
                StackName: "extension-layer"
                ActionMode: CHANGE_SET_EXECUTE
                RoleArn: !Sub arn:aws:iam::${DeployAccount}:role/PipelineAutomationRole
                Capabilities: CAPABILITY_NAMED_IAM
